$('.owl-carousel').owlCarousel({
    loop:true,
    margin:8,
    nav:false,
    responsive:{
        0:{
            items:1.1
        },
        400: {
            items:2.1
        },
        600:{
            items:3.1
        },
        1000:{
            items:4.1
        },
        1300:{
            items:5.1
        },
        1900:{
            items:10.1
        }
    }
})